name: My GitHub workflow
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
jobs:
  check-things:
    name: Check things
    runs-on: ubuntu-18.04
    steps: 
      - name: Print GITHUB_SHA and GITHUB_REF
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "GITHUB_REF=${GITHUB_REF}"
      - name: Print github context 
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "github.base_ref=${{ github.base_ref }}"
          echo "github.head_ref=${{ github.head_ref }}"
          echo "toJson(github)=${{ toJson(github) }}"
      - name: Print Go version
        run: |
          go version
