name: On push to master
on:
  push:
    branches:
      - master
      - test-pr
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-18.04
    steps:
      - name: Print github context JSON
        run: |
          echo "toJson(github)=${{ toJson(github) }}"
  push-a-commit:
    name: Push a commit
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "touch"
      - name: Push changes
        env:
          REMOTE_REPO: "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        run: |
          git push "${REMOTE_REPO}" HEAD:${{ github.ref }}
  create-release:
    name: Create release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: release-info
        name: Extract tag name
        run: |
          tag="v1.2.3-test-3"
          echo "::set-output name=tag::${tag}"
      - name: Tag the commit
        run: |
          git tag "${{ steps.release-info.outputs.tag }}" "${{ github.sha }}"
      - name: Push tag
        env:
          REMOTE_REPO: "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        run: |
          git push "${REMOTE_REPO}" --tags
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.release-info.outputs.tag }}"
          release_name: "${{ steps.release-info.outputs.tag }}"
